# We need test repeatability.
# We will achieve diversity by using a number of examples.
seed = 42

# NOTE: We extend the rules as the schema generation results improve.
[phases.examples]
enabled = true

[phases.coverage]
enabled = true

[phases.fuzzing]
enabled = true

[phases.stateful]
enabled = true

[generation]
max-examples = 100

[checks]
enabled = false
not_a_server_error.enabled = true
content_type_conformance.enabled = true
response_headers_conformance.enabled = true
response_schema_conformance.enabled = true
