# TODO: We extend the rules as the schema generation results improve.
[generation]
# Limit the number of generated examples per API operation to keep tests fast.
max-examples = 2

[checks]
# Docs: https://schemathesis.readthedocs.io/en/stable/reference/checks
# We will expand the checks as we implement the openapi schemageneration.
enabled = true

# Verifies the response status code is documented in the schema for the operation
status_code_conformance.enabled = false

# Verifies the API accepts valid request data.
positive_data_acceptance.enabled = false

# Verifies the API rejects requests when required headers are missing.
missing_required_header.enabled = false
