[project]
name = "django_modern_rest_pytest"
version = "0.1.0"
package-mode = true

[build-system]
requires = ["poetry-core>=2.1"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."pytest11"]
django_modern_rest = "django_modern_rest_pytest"

[packages]
